kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31000   # NodePort for web
    hostPort: 8080
    protocol: TCP
  - containerPort: 33000   # NodePort for MinIO API
    hostPort: 9000
    protocol: TCP
  - containerPort: 33001   # NodePort for MinIO Console
    hostPort: 9001
    protocol: TCP
- role: worker
- role: worker
