apiVersion: v1
kind: Service
metadata: { name: web, namespace: bank-pipeline }
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000
  selector: { app: web }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: web, namespace: bank-pipeline }
spec:
  replicas: 1
  selector: { matchLabels: { app: web } }
  template:
    metadata: { labels: { app: web } }
    spec:
      containers:
      - name: web
        image: docker.io/mohamed1780/web-tp-m2i:latest
        env:
        - { name: MYSQL_HOST, value: "mysql" }
        - { name: MYSQL_USER, value: "root" }
        - { name: MYSQL_PWD,  valueFrom: { secretKeyRef: { name: db-secrets, key: MYSQL_ROOT_PASSWORD } } }
