apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: bank-pipeline
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
  MYSQL_ROOT_PASSWORD: "root"
  MINIO_ROOT_USER: "minio"
  MINIO_ROOT_PASSWORD: "minio123"
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "root"
